#!/bin/bash
# Envrionemnt Variables
read -p "Build UI (true):" buildUI
if [ "$buildUI" = "true" ] || [ "$buildUI" = "1" ] || [ -z $buildUI ]; then
    buildUI=1
else
    buildUI=0
fi

read -p "Web Token (for management): " webToken

if [ -z $webToken ]; then
    webToken=1254
fi

read -p "Web Port (1254): " webPort
read -p "V2Ray Client Host: " v2rayServer
read -p "Clone V2Ray Config and Certificates from server (host address): " cloneConfig

if [ ! -z $cloneConfig ]; then
    read -p "Clone V2Ray Config and Certificates from server (user) (ubuntu): " cloneConfigUser
fi

read -p "Main Server Address (if this node is client): " serverAddress

if [ ! -z $serverAddress ]; then
    read -p "Server Name (main-server) : " serverName
    if [ -z $serverName ]; then
        serverName="main-server"
    fi
    read -p "Api Key : " apiKey
    read -p "Node ID : " nodeId
fi


export WEB_TOKEN=$webToken
export WEB_PORT=$webPort
export V2RAY_SERVER=$v2rayServer
export CLONE_CONFIG=$cloneConfig
export CLONE_CONFIG_USER=$cloneConfigUser
export API_KEY=$apiKey
export UI=$buildUI
export NODE_ID=$nodeId
export SERVER_ADDRESS=$serverAddress
export SERVER_NAME=$serverName

# Set time-zone
timedatectl set-timezone Asia/Tehran

# Install V2Fly
bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)

# Insall NVM
wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash

# Clone V2Ray Admin
git clone https://github.com/mdzzohrabi/v2ray-admin.git /home/v2ray-admin

# Install Node LTS
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
nvm install --lts

# Install V2Ray Admin Dependencies
npm i -g npm
npm i -g pm2
cd /home/v2ray-admin
npm i

# UI Build
if [[ $UI -ne 0 ]] || [ $UI = "1" ]; then
    cd src-ui
    npm i
    npm run build
    cd ../
fi
# End UI Build

# Run Services
sh bash/pm2

# Copy configuration
if [ ! -z $CLONE_CONFIG ]; then
    # Copy config
    scp $CLONE_CONFIG_USER@$CLONE_CONFIG:/usr/local/etc/v2ray/config.json /usr/local/etc/v2ray/config.json

    # Copy certs
    scp -r $CLONE_CONFIG_USER@$CLONE_CONFIG:/home/certs /home/certs

    echo "Configuration cloned from '$CLONE_CONFIG'"
fi

# Mirror node
if [ ! -z $API_KEY ]; then
    if [ ! -d /home/v2ray-admin/db ]; then
        mkdir /home/v2ray-admin/db
        chmod +777 /home/v2ray-admin/db
    fi

    echo "[{\"name\":\"$SERVER_NAME\",\"id\":\"$NODE_ID\",\"apiKey\":\"$API_KEY\",\"address\":\"$SERVER_ADDRESS\",\"type\":\"server\",\"sync\":true}]" > /home/v2ray-admin/db/server-nodes.json

    # Restart services
    pm2 restart all
fi

# Install Bandwidth Monitor tools
apt install vnstat

# Start v2ray server
service v2ray restart